version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork
    environment:
      - APP_ENV=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=chat_db
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  migrate:
    image: migrate/migrate
#    command: -path /migrations -database "postgres://postgres:1234@postgres_container:5432/chat_db?sslmode=disable" up
    command: -path /migrations -database "postgres://postgres:1234@postgres:5432/chat_db?sslmode=disable" up
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - ./models/migrations:/migrations

volumes:
  postgres-data:
  logs:

networks:
  mynetwork:
    driver: bridge


