// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the ILogger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// DPanic provides a mock function for the type MockLogger
func (_mock *MockLogger) DPanic(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_DPanic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DPanic'
type MockLogger_DPanic_Call struct {
	*mock.Call
}

// DPanic is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) DPanic(args ...interface{}) *MockLogger_DPanic_Call {
	return &MockLogger_DPanic_Call{Call: _e.mock.On("DPanic",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_DPanic_Call) Run(run func(args ...interface{})) *MockLogger_DPanic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_DPanic_Call) Return() *MockLogger_DPanic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DPanic_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_DPanic_Call {
	_c.Run(run)
	return _c
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Debug(args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(args ...interface{})) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Error(args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(args ...interface{})) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockLogger
func (_mock *MockLogger) Fatal(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Fatal(args ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(args ...interface{})) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Info(args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// InitLogger provides a mock function for the type MockLogger
func (_mock *MockLogger) InitLogger() {
	_mock.Called()
	return
}

// MockLogger_InitLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitLogger'
type MockLogger_InitLogger_Call struct {
	*mock.Call
}

// InitLogger is a helper method to define mock.On call
func (_e *MockLogger_Expecter) InitLogger() *MockLogger_InitLogger_Call {
	return &MockLogger_InitLogger_Call{Call: _e.mock.On("InitLogger")}
}

func (_c *MockLogger_InitLogger_Call) Run(run func()) *MockLogger_InitLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_InitLogger_Call) Return() *MockLogger_InitLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InitLogger_Call) RunAndReturn(run func()) *MockLogger_InitLogger_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function for the type MockLogger
func (_mock *MockLogger) Panic(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockLogger_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Panic(args ...interface{}) *MockLogger_Panic_Call {
	return &MockLogger_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Panic_Call) Run(run func(args ...interface{})) *MockLogger_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Panic_Call) Return() *MockLogger_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Panic_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Panic_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - args
func (_e *MockLogger_Expecter) Warn(args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(args ...interface{})) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]interface{})
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(args ...interface{})) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}
