// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type User struct {
	ID        int32
	Name      string
	Email     string
	Phone     string
	Password  string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
