name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod download

      - name: Generate Swagger docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init --generalInfo cmd/main.go --output docs

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -o main ./cmd

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:k6io/k6
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 load test
        run: k6 run tests/load/load_test_create.js